name: Radicalbit Bot
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
  build-api:
    if: ${{ github.event.comment.body == '/build-api' || github.event.comment.body == '/build-all' }}
    uses: ./.github/workflows/docker.yaml
    with:
      push: false
      context: ./api
      image: test-be
      tag: 'latest'
    secrets:
      USERNAME: ${{ secrets.DOCKER_HUB_USER }}
      PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}
      ORGANIZATION: ${{ secrets.DOCKER_HUB_ORG }}
  
  echo-job-url:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo
        run: |
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  