name: Radicalbit Bot
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
  build-api:
    if: ${{ github.event.comment.body == '/build-api' || github.event.comment.body == '/build-all' }}
    uses: ./.github/workflows/docker.yaml
    with:
      push: false
      context: ./api
      image: test-be
      tag: 'latest'
    secrets:
      USERNAME: ${{ secrets.DOCKER_HUB_USER }}
      PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}
      ORGANIZATION: ${{ secrets.DOCKER_HUB_ORG }}

  comment-job-link:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issue_comment' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_HUB_PAT }}
    steps:
      - name: Comment on issue
        run: |
          export JOB_LINK="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo -n "{\"body\":\"### Running Job\nRequested JOB is running.\n\nView the job [here]($JOB_LINK)\"}" > result.json
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            ${{ github.event.comment.issue_url }} \
            -d @result.json