name: Radicalbit Bot
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
  build-api:
    if: ${{ github.event.comment.body == '/build-api' || github.event.comment.body == '/build-all' }}
    uses: ./.github/workflows/docker.yaml
    with:
      push: false
      context: ./api
      image: test-be
      tag: 'latest'
    secrets:
      USERNAME: ${{ secrets.DOCKER_HUB_USER }}
      PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}
      ORGANIZATION: ${{ secrets.DOCKER_HUB_ORG }}  
  